org: stephane71
app: scraper
service: ffa-scraper

useDotenv: true

package:
  exclude:
    - node_modules/**

plugins:
  - serverless-offline
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-3
  memorySize: 128

  iamManagedPolicies:
    - arn:aws:iam::514894570076:policy/La-Foulee-ffa-scraper-read-s3-bucket
    - arn:aws:iam::514894570076:policy/La-Foulee-ffa-scraper-write-s3-bucket
    - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

functions:
  download-sources:
    handler: services/download-sources/index.handler
    timeout: 30
    environment:
      S3_DESTINATION: ${param:S3_BUCKET_FFA_SCRAPER}
    events:
      - http:
          path: /download-sources/{year}/{dep}
          method: get
          # Remove it to test => doesn't work in AWS API Gateway console: test
          # authorizer: aws_iam
          cors: true
          request:
            parameters:
              paths:
                year: true
                dep: true

  extract-events:
    handler: services/extract-events/index.handler
    timeout: 15
    memorySize: 192
    environment:
      S3_DESTINATION: ${param:S3_BUCKET_FFA_SCRAPER_EXTRACT_EVENTS}
    events:
      - s3:
          bucket: ${param:S3_BUCKET_FFA_SCRAPER}
          existing: true

  update-event-location:
    handler: services/update-event-location/index.handler
    memorySize: 192
    #role: arn:aws:iam::514894570076:role/La-Foulee-Scraper-Execute-PlacesAPI
    environment:
      S3_DESTINATION: ${param:S3_BUCKET_FFA_SCRAPER_EVENTS_WITH_LOCATION}
      PLACE_PROXY_API_URL: ${param:PLACE_PROXY_API_URL}
    events:
      - s3:
          bucket: ${param:S3_BUCKET_FFA_SCRAPER_EXTRACT_EVENTS}
          existing: true
