org: stephane71
app: scraper
service: ffa-scraper

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-3
  memorySize: 128

  #  iamManagedPolicies:
  #    - arn:aws:iam::514894570076:policy/La-Foulee-ffa-scraper-read-s3-bucket
  #    - arn:aws:iam::514894570076:policy/La-Foulee-ffa-scraper-write-s3-bucket
  #    - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  #    - arn:aws:iam::514894570076:policy/La-Foulee-PlacesAPI-ExecuteAPI-dev

  ## IAM ROLE - ACCESS TO DYNAMODB TABLE ##
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
            - 'execute-api:Invoke'
          Resource:
            - arn:aws:s3:::ffa-scraper*/*
            - arn:aws:execute-api:${self:custom.runningEventsApi.region}:514894570076:${self:custom.runningEventsApi.id}/dev/GET/*
            - arn:aws:execute-api:${self:custom.runningEventsApi.region}:514894570076:${self:custom.runningEventsApi.id}/dev/PUT/*
            - arn:aws:execute-api:${self:custom.runningEventsApi.region}:514894570076:${self:custom.runningEventsApi.id}/dev/DELETE/*

functions:
  download-sources:
    handler: services/download-sources/index.handler
    timeout: 30
    maximumRetryAttempts: 0
    environment:
      S3_DESTINATION: ${param:S3_BUCKET_FFA_SCRAPER}
    events:
      - http:
          path: /download-sources/{year}/{dep}
          method: get
          # Remove it to test => doesn't work in AWS API Gateway console: test
          # authorizer: aws_iam
          cors: true
          request:
            parameters:
              paths:
                year: true
                dep: true

  extract-events:
    handler: services/extract-events/index.handler
    timeout: 15
    memorySize: 192
    maximumRetryAttempts: 0
    environment:
      S3_DESTINATION: ${param:S3_BUCKET_FFA_SCRAPER_EXTRACT_EVENTS}
    events:
      - s3:
          bucket: ${param:S3_BUCKET_FFA_SCRAPER}

  update-event-location:
    handler: services/update-event-location/index.handler
    timeout: 15
    memorySize: 192
    maximumRetryAttempts: 0
    environment:
      S3_DESTINATION: ${param:S3_BUCKET_FFA_SCRAPER_EVENTS_WITH_LOCATION}
      PLACES_API_URL: ${param:PLACES_API_URL}
      PLACES_API_REGION: ${param:PLACES_API_REGION}
    events:
      - s3:
          bucket: ${param:S3_BUCKET_FFA_SCRAPER_EXTRACT_EVENTS}

  update-event-details:
    handler: services/update-event-details/index.handler
    maximumRetryAttempts: 0
    environment:
      S3_DESTINATION: ${param:S3_BUCKET_FFA_SCRAPER_EVENTS_WITH_DETAILS}
    events:
      - s3: ${param:S3_BUCKET_FFA_SCRAPER_EVENTS_WITH_LOCATION}

  put-event:
    handler: services/put-event/index.handler
    maximumRetryAttempts: 0
    timeout: 15
    environment:
      RUNNING_EVENTS_API_ID : ${self:custom.runningEventsApi.id}
      RUNNING_EVENTS_API_REGION: ${self:custom.runningEventsApi.region}
    events:
      - s3: ${param:S3_BUCKET_FFA_SCRAPER_EVENTS_WITH_DETAILS}

custom:
  runningEventsApi:
    id: faw96n173k
    region: eu-west-3